services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - CompaniesData-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CompaniesDataDb

volumes:
  CompaniesData-db-volume:
